Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from particula import u
from particula.environment import Environment

EnvWrong = Environment(temperature=300*u.m) # will raise an error
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_2064/3153459865.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;32mfrom[0m [0mparticula[0m[0;34m.[0m[0menvironment[0m [0;32mimport[0m [0mEnvironment[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[0;32m----> 4[0;31m [0mEnvWrong[0m [0;34m=[0m [0mEnvironment[0m[0;34m([0m[0mtemperature[0m[0;34m=[0m[0;36m300[0m[0;34m*[0m[0mu[0m[0;34m.[0m[0mm[0m[0;34m)[0m [0;31m# will raise an error[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/particula/environment.py[0m in [0;36m__init__[0;34m(self, **kwargs)[0m
[1;32m     50[0m [0;34m[0m[0m
[1;32m     51[0m         self.temperature = in_temperature(
[0;32m---> 52[0;31m             [0mkwargs[0m[0;34m.[0m[0mget[0m[0;34m([0m[0;34m"temperature"[0m[0;34m,[0m [0;36m298.15[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     53[0m         )
[1;32m     54[0m         self.reference_viscosity = in_viscosity(

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/particula/util/input_handling.py[0m in [0;36min_temperature[0;34m(temp)[0m
[1;32m     75[0m [0;34m[0m[0m
[1;32m     76[0m [0;31m# pylint: disable=missing-docstring, multiple-statements[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 77[0;31m [0;32mdef[0m [0min_temperature[0m[0;34m([0m[0mtemp[0m[0;34m)[0m[0;34m:[0m [0;32mreturn[0m [0min_handling[0m[0;34m([0m[0mtemp[0m[0;34m,[0m [0mu[0m[0;34m.[0m[0mK[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     78[0m [0;32mdef[0m [0min_viscosity[0m[0;34m([0m[0mvis[0m[0;34m)[0m[0;34m:[0m [0;32mreturn[0m [0min_handling[0m[0;34m([0m[0mvis[0m[0;34m,[0m [0mu[0m[0;34m.[0m[0mkg[0m[0;34m/[0m[0mu[0m[0;34m.[0m[0mm[0m[0;34m/[0m[0mu[0m[0;34m.[0m[0ms[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     79[0m [0;32mdef[0m [0min_pressure[0m[0;34m([0m[0mpres[0m[0;34m)[0m[0;34m:[0m [0;32mreturn[0m [0min_handling[0m[0;34m([0m[0mpres[0m[0;34m,[0m [0mu[0m[0;34m.[0m[0mPa[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/particula/util/input_handling.py[0m in [0;36min_handling[0;34m(value, units)[0m
[1;32m     62[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     63[0m             raise ValueError(
[0;32m---> 64[0;31m                 [0;34mf"\n\t"[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     65[0m                 [0;34mf"Input has unsupported units.\n\t"[0m[0;34m[0m[0;34m[0m[0m
[1;32m     66[0m                 [0;34mf"Input must have units equivlanet to {units};\n\t"[0m[0;34m[0m[0;34m[0m[0m

[0;31mValueError[0m: 
	Input has unsupported units.
	Input must have units equivlanet to kelvin;
	otherwise, if dimensionless, it will
	be assigned kelvin.

ValueError: 
	Input has unsupported units.
	Input must have units equivlanet to kelvin;
	otherwise, if dimensionless, it will
	be assigned kelvin.


