Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from particula import u
from particula.vapor import Vapor

VapOne = Vapo(temperature=300) 
print("temperature is ", VapOne.temperature) # will print 300 K
print("pressure is ", VapOne.pressure) # will print 101325 Pa (kg/m/s^2)
print("vapor radius is ", VapOne.vapor_radius)  # will print 1.6 nm
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_2084/2950159680.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;32mfrom[0m [0mparticula[0m[0;34m.[0m[0mvapor[0m [0;32mimport[0m [0mVapor[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[0;32m----> 4[0;31m [0mVapOne[0m [0;34m=[0m [0mVapo[0m[0;34m([0m[0mtemperature[0m[0;34m=[0m[0;36m300[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0mprint[0m[0;34m([0m[0;34m"temperature is "[0m[0;34m,[0m [0mVapOne[0m[0;34m.[0m[0mtemperature[0m[0;34m)[0m [0;31m# will print 300 K[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0mprint[0m[0;34m([0m[0;34m"pressure is "[0m[0;34m,[0m [0mVapOne[0m[0;34m.[0m[0mpressure[0m[0;34m)[0m [0;31m# will print 101325 Pa (kg/m/s^2)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'Vapo' is not defined
NameError: name 'Vapo' is not defined

